export const MOCK_REVIEWS = [
  {
    id: 1,
    name: '김지은',
    rating: 5,
    date: '2026-03-20',
    content: '정말 아름다운 곳이었어요. 산책하기 너무 좋았습니다!',
  },
  {
    id: 2,
    name: '이민준',
    rating: 4,
    date: '2026-03-18',
    content: '경치가 훌륭하고 공기도 맑아서 힐링됐어요.',
  },
  {
    id: 3,
    name: '박서연',
    rating: 5,
    date: '2026-03-15',
    content: '가족과 함께 방문했는데 아이들이 너무 좋아했어요.',
  },
  {
    id: 4,
    name: '최도윤',
    rating: 3,
    date: '2026-03-12',
    content: '주말엔 사람이 너무 많아요. 평일 방문 추천합니다.',
  },
  {
    id: 5,
    name: '정하은',
    rating: 5,
    date: '2026-03-10',
    content: '사진 찍기 정말 좋은 곳이에요. 강력 추천!',
  },
  {
    id: 6,
    name: '강지호',
    rating: 4,
    date: '2026-03-08',
    content: '주변 음식점도 맛있고 전체적으로 만족스러웠어요.',
  },
  {
    id: 7,
    name: '윤서아',
    rating: 5,
    date: '2026-03-05',
    content: '처음 방문인데 또 오고 싶을 만큼 좋았습니다.',
  },
  {
    id: 8,
    name: '임현우',
    rating: 4,
    date: '2026-03-02',
    content: '시설이 잘 관리되어 있고 깨끗했어요.',
  },
  {
    id: 9,
    name: '오지수',
    rating: 2,
    date: '2026-02-28',
    content: '주차 공간이 너무 부족해서 불편했어요.',
  },
  {
    id: 10,
    name: '한소율',
    rating: 5,
    date: '2026-02-25',
    content: '해질 무렵 방문하면 노을이 정말 장관이에요.',
  },
  {
    id: 11,
    name: '신예준',
    rating: 4,
    date: '2026-02-22',
    content: '조용하고 분위기 좋아서 데이트 코스로 최고!',
  },
  {
    id: 12,
    name: '배나연',
    rating: 5,
    date: '2026-02-20',
    content: '사계절 모두 다른 매력이 있는 곳이에요.',
  },
  {
    id: 13,
    name: '류태양',
    rating: 3,
    date: '2026-02-17',
    content: '볼거리는 많지만 편의시설이 좀 부족한 것 같아요.',
  },
  {
    id: 14,
    name: '전아린',
    rating: 5,
    date: '2026-02-14',
    content: '혼자 와도 충분히 즐길 수 있는 곳이에요.',
  },
  {
    id: 15,
    name: '고민재',
    rating: 4,
    date: '2026-02-11',
    content: '자전거 타기 좋은 길이 잘 정비되어 있어요.',
  },
  {
    id: 16,
    name: '남지우',
    rating: 5,
    date: '2026-02-08',
    content: '아침 일찍 오면 안개 낀 풍경이 환상적이에요.',
  },
  {
    id: 17,
    name: '문하준',
    rating: 4,
    date: '2026-02-05',
    content: '입장료 대비 볼거리가 풍부해서 만족스러워요.',
  },
  {
    id: 18,
    name: '서이나',
    rating: 3,
    date: '2026-02-02',
    content: '사람이 많아 복잡하지만 경치는 정말 좋아요.',
  },
  {
    id: 19,
    name: '조현빈',
    rating: 5,
    date: '2026-01-30',
    content: '겨울에도 운치 있어서 좋았어요. 강추합니다!',
  },
  {
    id: 20,
    name: '황소이',
    rating: 4,
    date: '2026-01-27',
    content: '다음에 또 방문하고 싶은 곳이에요. 만족!',
  },
]
